### PR TITLE
Fix my mistake

### PR DESCRIPTION
**Pull request by bonnedav**
In my last PR I made a mistake that causes a potential problem. This PR fixes it and redoes what I was trying to do.

### CODE REVIEW

**Comment by The-Voidwalker** [comment]
Handled in 19d326f

**Comment by bonnedav** [comment]
@The-Voidwalker I was thinking to all other group to remove themself as well that is what this does. it does what you did for all groups except ones that revoke rights (exampleuser, chatblocked) and ones that can remove themselves from all users already (sysadmin, steward, bureaucrat). so that say patroller can remove patroller form their own account. but it's your call, thank you for fixing and reading this.

**Comment by The-Voidwalker** [comment]
I think any right except sysop can already be removed by the user in question without real issues.

**Comment by bonnedav** [comment]
True, I was thinking about a normal wiki. On here, most everyone has sysop anyway. Why did your commit include crat then? they can remove crat form anybody including themselves alrady. thank you for helping and sorry about my mistake. I just realised the problem when I got home.

**Comment by The-Voidwalker** [comment]
Yeah, no problem. I removed the crat bit, it is redundant (didn't realize that at first).

**Comment by bonnedav** [comment]
Also, wish I know what was going on with editor and reviewer, the changes did not do anything. And they were just the defaults from the plugin and should not need to be in the config but aren't working even then.

**Pull request closed without merging**
