### PR TITLE
Enable TorBlock extension

### PR DESCRIPTION
**Pull request by Pillowfluffyhead**
Recent vandalism from various open proxies

### CODE REVIEW

**Comment by MacFan4000** [comment]
It first must be added to the extensions repo as a submodule.

**Comment by Pillowfluffyhead** [comment]
@MacFan4000 how do you do that?

**Comment by MacFan4000** [comment]
Using the command line on your local computer. https://github.com/blog/2104-working-with-submodules

**Comment by Pillowfluffyhead** [comment]
I'm not very sysadmin literate. If you can do it that would be great, otherwise we can put this on hold.

**Pull request closed without merging**
